#!/bin/bash
#
# start-build-vm.sh -- size and launch the Helios build VM, choosing guest
# RAM from live host memory so a long illumos build doesn't starve the
# desktop. Wraps helios-engvm's create.sh.
#
# Lives in the tracked workspace-root repo (infra/), NOT in the upstream
# helios-engvm clone. It drives create.sh in the clone via $ENGVM_DIR and
# writes one generated config there ($ENGVM_DIR/config/build.sh, which is
# git-excluded in that clone).
#
# What it does:
#   1. Reads /proc/meminfo MemAvailable (kernel's estimate of allocatable
#      RAM without swapping -- already accounts for other running VMs and
#      reclaimable cache).
#   2. guest_RAM = clamp(MemAvailable - HOST_RESERVE_GB, MIN_GB, MAX_GB).
#      Under a normal desktop this lands ~12 GB; drops when busy, rises
#      (capped) when roomy.
#   3. Reports memory-heavy processes (other QEMU, ollama, boinc) so you
#      can free them first -- it does NOT kill anything.
#   4. Ensures the seed image + libvirt 'default' network are present.
#   5. Writes $ENGVM_DIR/config/build.sh (VCPU/MEM/SIZE deltas, layered by
#      create.sh over config/defaults.sh) and runs create.sh build.
#
# Tune the knobs below to taste.

set -o pipefail
set -o errexit

# --- Tunable knobs -----------------------------------------------------
MIN_GB=8            # illumos build floor -- never give the guest less
MAX_GB=16           # host protection -- never give the guest more
HOST_RESERVE_GB=8   # RAM kept free for your desktop to grow into
VCPU=12             # 32 threads on this host; build parallelism = 2 + NCPUS
SIZE=200G           # qcow2 VIRTUAL ceiling (thin -- grows on demand)
CONFIG_NAME=build   # writes config/build.sh, passes 'build' to create.sh
# -----------------------------------------------------------------------

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
source "$SCRIPT_DIR/../config.sh"

if [ ! -x "$ENGVM_DIR/create.sh" ]; then
    echo "ERROR: helios-engvm clone not found at $ENGVM_DIR" >&2
    echo "Clone oxidecomputer/helios-engvm there first (see workspace README)." >&2
    exit 1
fi

# Inherit VM/POOL/INPUT_IMAGE so our preflight checks match create.sh.
. "$ENGVM_DIR/config/defaults.sh"

# --- 1. Assess host memory --------------------------------------------
avail_kb=$(awk '/^MemAvailable:/{print $2}' /proc/meminfo)
total_kb=$(awk '/^MemTotal:/{print $2}' /proc/meminfo)
avail_gb=$(( avail_kb / 1024 / 1024 ))
total_gb=$(( total_kb / 1024 / 1024 ))
echo "Host memory: ${total_gb} GB total, ${avail_gb} GB available now."

# --- 2. Report memory-heavy processes (informational only) ------------
echo "Memory-heavy processes competing with the build VM:"
ps -eo rss,pid,comm --sort=-rss 2>/dev/null | awk '
    NR>1 && ($3 ~ /qemu/ || $3 ~ /ollama/ || $3 ~ /boinc/) {
        printf "  %-18s pid %-7s %6.1f GB\n", $3, $2, $1/1024/1024
    }' || true
echo "  (free these and re-run if you want the guest to get more RAM)"

# --- 3. Compute guest RAM ---------------------------------------------
mem_gb=$(( avail_gb - HOST_RESERVE_GB ))
[ "$mem_gb" -gt "$MAX_GB" ] && mem_gb=$MAX_GB
if [ "$mem_gb" -lt "$MIN_GB" ]; then
    echo >&2
    echo "ERROR: only ${avail_gb} GB available; after the ${HOST_RESERVE_GB} GB host" >&2
    echo "reserve, the guest would get < the ${MIN_GB} GB build floor." >&2
    echo "Free RAM (close VMs/tabs, 'sudo systemctl stop ollama', etc) and retry." >&2
    exit 1
fi
echo
echo "==> guest RAM: ${mem_gb} GB  (= ${avail_gb} avail - ${HOST_RESERVE_GB} reserve, clamped to [${MIN_GB},${MAX_GB}])"
echo "==> vCPU: ${VCPU}   disk ceiling: ${SIZE} (thin qcow2)"

# --- 4. Preflight: seed image + libvirt network -----------------------
if [ ! -f "$ENGVM_DIR/input/$INPUT_IMAGE" ]; then
    echo
    echo "Seed image $INPUT_IMAGE not found -- downloading via engvm download.sh ..."
    ( cd "$ENGVM_DIR" && ./download.sh )
fi

if ! virsh net-info default 2>/dev/null | grep -q 'Active:.*yes'; then
    echo "Activating libvirt 'default' network ..."
    virsh net-start default || true
fi

# --- 5. Write the generated config delta and launch -------------------
cfg="$ENGVM_DIR/config/${CONFIG_NAME}.sh"

# Ensure the generated config is git-excluded in the upstream-mirror clone
# so it never shows as untracked noise or risks being committed. Idempotent,
# and self-healing on a fresh clone where it hasn't been excluded yet.
if [ -d "$ENGVM_DIR/.git" ]; then
    exclude_file="$ENGVM_DIR/.git/info/exclude"
    exclude_pat="/config/${CONFIG_NAME}.sh"
    mkdir -p "$(dirname "$exclude_file")"
    if ! grep -qxF "$exclude_pat" "$exclude_file" 2>/dev/null; then
        printf '\n# Generated by infra/scripts/vm/start-build-vm.sh (runtime artifact, never commit)\n%s\n' \
            "$exclude_pat" >> "$exclude_file"
        echo "git-excluded $exclude_pat in the helios-engvm clone."
    fi
fi

cat > "$cfg" <<EOF
#
# GENERATED by infra/scripts/vm/start-build-vm.sh -- do not hand-edit;
# tune the knobs in that script instead. Layered over config/defaults.sh.
#
VCPU=$VCPU
MEM=\$(( $mem_gb * 1024 * 1024 ))
SIZE=$SIZE
EOF
echo "Wrote $cfg (MEM=${mem_gb} GB, VCPU=${VCPU}, SIZE=${SIZE})"
echo

exec "$ENGVM_DIR/create.sh" "$CONFIG_NAME"
